// import Mongoose for MongoDB object modelling
const mongoose = require("mongoose");

// define the schema for Category model
const Schema = mongoose.Schema;

// create new schema for Category model
const categorySchema = new Schema({
  // note: _id is automatically generated by Mongoose

  // field for category name
  name: {
    type: String,
    // name input is required
    required: true,
  },

  // field for category colour
  colour: {
    type: String,
    // colour input is required
    required: true,
  },
});

// define Category model based on schema
// use mongoose.models.Category if already defined, else define a new model
const Category =
  mongoose.models.Category || mongoose.model("Category", categorySchema);

// export Category model
module.exports = Category;
